# Generated by Django 2.1.5 on 2020-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
            ],
        ),
    ]
