# Generated by Django 2.1.5 on 2020-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='number',
            field=models.BigIntegerField(verbose_name='Age'),
        ),
    ]
