# Generated by Django 2.1.5 on 2020-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_auto_20200524_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
