# Generated by Django 2.1.5 on 2020-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_dummy_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='Active',
            field=models.NullBooleanField(),
        ),
    ]
