# Generated by Django 2.1.5 on 2020-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_auto_20200524_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='Active',
            field=models.BooleanField(null=True),
        ),
    ]
