# Generated by Django 2.1.5 on 2020-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0007_dummy_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
