# Generated by Django 2.1.5 on 2020-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0011_dummy_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='UserName',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='Unknown', max_length=5),
        ),
    ]
