# Generated by Django 2.1.5 on 2020-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0012_auto_20200524_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='UserName',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='unknown', max_length=5),
        ),
    ]
