# Generated by Django 2.1.5 on 2020-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0014_auto_20200524_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='UserName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='options',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
