# Generated by Django 2.1.5 on 2020-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0016_auto_20200524_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='files',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
