# Generated by Django 2.1.5 on 2020-05-24 16:56

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0017_auto_20200524_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, validators=[CoreApp.models.validate_number]),
        ),
    ]
