# Generated by Django 2.1.5 on 2020-05-24 16:57

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0018_auto_20200524_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='number',
            field=models.BigIntegerField(validators=[CoreApp.models.validate_number], verbose_name='Age'),
        ),
    ]
