# Generated by Django 2.1.5 on 2020-05-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0020_dummy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='UserName',
            field=models.CharField(error_messages={'unique': 'Username already taked try again!!!!'}, help_text='Valid username in alphabets only...', max_length=50, unique=True),
        ),
    ]
