# Generated by Django 2.1.5 on 2020-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0022_auto_20200525_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
