# Generated by Django 2.1.5 on 2020-05-27 17:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0023_auto_20200525_1204'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dummy',
            managers=[
                ('modelManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
