# Generated by Django 2.1.5 on 2020-06-01 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Only Numericals is allowed')]),
        ),
    ]
