# Generated by Django 2.1.5 on 2020-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0002_auto_20200601_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PizzaName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topname', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='Relationships.Toppings'),
        ),
    ]
