# Generated by Django 2.1.5 on 2020-06-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobby', models.CharField(blank=True, max_length=5)),
                ('Favourite_Sport', models.CharField(blank=True, max_length=10)),
                ('Working_Place', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=10)),
                ('Experience', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
