# Generated by Django 2.1.5 on 2020-06-12 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='Company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='Favourite_Sport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='Hobby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='Working_Place',
            field=models.CharField(max_length=100),
        ),
    ]
