# Generated by Django 2.1.5 on 2020-06-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManytoMany', '0002_auto_20200602_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManytoMany.City'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ProductTags',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
