# Generated by Django 2.1.5 on 2020-05-26 16:57

import classBasedCoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classBasedCoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='about',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='login',
            name='description',
            field=models.TextField(max_length=50, validators=[classBasedCoreApp.models.customvalidate]),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
