# Generated by Django 2.1.5 on 2020-05-26 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classBasedCoreApp', '0002_auto_20200526_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='publishedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
