# Generated by Django 2.1.5 on 2020-05-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classBasedCoreApp', '0005_formmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='formmodel',
            old_name='lastanme',
            new_name='lastname',
        ),
    ]
